@Anamnesis_Server_HostAddress = http://localhost:5000

GET {{Anamnesis_Server_HostAddress}}/namespace/name/system/versions
Accept: application/json

###

GET {{Anamnesis.Server_HostAddress}}/todos/1
Accept: application/json

###
