@Anamnesis_HostAddress = http://localhost:80

GET {{Anamnesis_HostAddress}}/.well-known/terraform.json
Accept: application/json

###

GET {{Anamnesis_HostAddress}}/namespace/name/system/versions
Accept: application/json

###
